MAX_TRANSCRIPT_WORD_COUNT = 3000
MAX_TOTAL_SCRAPE_WORD_COUNT = 3000
MAX_IMAGES_TO_INCLUDE = 10
MAX_LINKS_TO_TAKE = 6
MIN_LINKS_TO_TAKE = 3
AUDIO_TRANSCRIBE_SIZE = "small"
BASE_CACHE_DIR = "./data/audio_cache"

isHeadless = True
POLLINATIONS_ENDPOINT = "https://gen.pollinations.ai/v1/chat/completions"

MAX_SESSIONS = 1000
SESSION_TTL_MINUTES = 30

RAG_CONTEXT_REFRESH = True

MODEL_POOL_SIZE = 1
MODEL_MAX_TABS = 20
MODEL_CACHE_CLEANUP_MINUTES = 30
MODEL_CACHE_MAX_AGE_MINUTES = 60

LLM_MODEL = "gemini-fast"
LLM_MAX_TOKENS = 3000
LLM_TEMPERATURE = 0.7
LLM_TOP_P = 1.0

SEARCH_MAX_RESULTS = 8
YOUTUBE_MAX_VIDEOS = 2
IMAGE_SEARCH_MAX = 10
FETCH_TIMEOUT = 30

PARALLEL_WORKERS = 10
REQUEST_TIMEOUT = 300
EMBEDDING_BATCH_SIZE = 64
EMBEDDING_DIVERSITY = 0.4

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE = None

ENABLE_WEBSOCKET_STREAMING = True
ENABLE_ENTITY_EXTRACTION = True
ENABLE_RELATIONSHIP_DETECTION = True

EMBEDDINGS_DIR = "./data/embeddings"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
EMBEDDING_BATCH_SIZE = 32

CHUNK_SIZE = 600
CHUNK_OVERLAP = 60

SEMANTIC_CACHE_DIR = "./data/cache"
SEMANTIC_CACHE_TTL_SECONDS = 3600
SEMANTIC_CACHE_SIMILARITY_THRESHOLD = 0.90
X_REQ_ID_SLICE_SIZE = 12

RETRIEVAL_TOP_K = 5
SESSION_SUMMARY_THRESHOLD = 6

PERSIST_VECTOR_STORE_INTERVAL = 300

CONVERSATION_CACHE_DIR = "./data/cache/conversation"
CACHE_WINDOW_SIZE = 10
CACHE_COMPRESSION_ENABLED = True
CACHE_SIMILARITY_THRESHOLD = 0.85
CACHE_MAX_ENTRIES = 50
CACHE_TTL_SECONDS = 1800
CACHE_EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
CACHE_MIN_QUERY_LENGTH = 10
CACHE_COMPRESSION_METHOD = "zlib"
REQUEST_ID_LEGACY_SLICE_SIZE = 10
REQUEST_ID_HEX_SLICE_SIZE = 8
LOG_MESSAGE_QUERY_TRUNCATE = 50
LOG_MESSAGE_CONTEXT_TRUNCATE = 100
LOG_MESSAGE_LONG_TRUNCATE = 150
LOG_MESSAGE_PREVIEW_TRUNCATE = 200
LOG_ENTRY_ID_DISPLAY_SIZE = 8
IMAGE_SEARCH_QUERY_WORDS_LIMIT = 15
ERROR_MESSAGE_TRUNCATE = 100
ERROR_CONTEXT_TRUNCATE = 150
