MAX_TRANSCRIPT_WORD_COUNT = 3000
MAX_TOTAL_SCRAPE_WORD_COUNT = 3000
MAX_IMAGES_TO_INCLUDE = 4
MAX_LINKS_TO_TAKE = 6
AUDIO_TRANSCRIBE_SIZE = "small"
BASE_CACHE_DIR = "./cached_audio"

isHeadless = True
POLLINATIONS_ENDPOINT = "https://gen.pollinations.ai/v1/chat/completions"

MAX_SESSIONS = 1000
SESSION_TTL_MINUTES = 30

RAG_CONTEXT_REFRESH = True

MODEL_POOL_SIZE = 1
MODEL_MAX_TABS = 20
MODEL_CACHE_CLEANUP_MINUTES = 30
MODEL_CACHE_MAX_AGE_MINUTES = 60

LLM_MODEL = "gemini-fast"
LLM_MAX_TOKENS = 3000
LLM_TEMPERATURE = 0.7
LLM_TOP_P = 1.0

SEARCH_MAX_RESULTS = 8
YOUTUBE_MAX_VIDEOS = 2
IMAGE_SEARCH_MAX = 5
FETCH_TIMEOUT = 30

PARALLEL_WORKERS = 10
REQUEST_TIMEOUT = 300
EMBEDDING_BATCH_SIZE = 64
EMBEDDING_DIVERSITY = 0.4

LOG_LEVEL = "INFO"
LOG_FORMAT = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
LOG_FILE = None

ENABLE_WEBSOCKET_STREAMING = True
ENABLE_ENTITY_EXTRACTION = True
ENABLE_RELATIONSHIP_DETECTION = True

EMBEDDINGS_DIR = "./embeddings"
EMBEDDING_MODEL = "sentence-transformers/all-MiniLM-L6-v2"
EMBEDDING_DIMENSION = 384
EMBEDDING_BATCH_SIZE = 32

CHUNK_SIZE = 600
CHUNK_OVERLAP = 60

SEMANTIC_CACHE_TTL_SECONDS = 3600
SEMANTIC_CACHE_SIMILARITY_THRESHOLD = 0.90

RETRIEVAL_TOP_K = 5
SESSION_SUMMARY_THRESHOLD = 6

PERSIST_VECTOR_STORE_INTERVAL = 300
